config/routes.rb
Rails.application.routes.draw do

  root 'myurls#index'

  resources :myurls

end

app/models/myurl.rb
class Myurl < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/myurls_controller.rb
class MyurlsController < ApplicationController
before_action :set_review, only: [:show]
  def index
    @myurls = Myurl.all
  end

  def show
  redirect_to  @myurl.togo
  end

  def new
    @myurl = Myurl.new
  end

  def create
    @myurl = Myurl.create(myurl_params)
    redirect_to myurls_path
  end

 private

  def set_review
    @myurl = Myurl.find(params[:id])
  end

  def myurl_params
      params.require(:myurl).permit(:name, :togo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myurls_helper.rb
module MyurlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urlshortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/myurls/create.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New</title>
  </head>
  <body>
    <h1>Create</h1>
  </body>
</html>

app/views/myurls/index.html.erb
<h1>Index</h1>

<% @myurls.each do |x| %>
<%= x.id %><br>
<%= x.name %><br>
<%= x.togo %><br>
<%= link_to 'Go To Page', myurl_path(x) %><br>
<% end %>
<%= link_to 'Create New Url', new_myurl_path %>

app/views/myurls/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> Create Shortcut </h1>
    <%= form_for @myurl do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :Where_To %>
    <%= f.text_field :togo %>
    <%= f.submit "Do it!", class: 'Myurl'%>
    <% end %>
  </body>
</html>

app/views/myurls/show.html.erb
<!-- <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New</title>
  </head>
  <body>
    <h1>show</h1>
  </body>
</html> -->